In [1]:
import pandas as pd

df=pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/channelInfo.csv')
df_video =pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/videoInfo.csv')

In [5]:
df['ct']=pd.to_datetime(df['ct'])
df_video['ct']=pd.to_datetime(df_video['ct'])
df_video['videoname'].value_counts()

videoname
 공범 EP1    3492
 공범 EP2    3204
 공범 EP3    2568
 공범 EP4    2280
 공범 EP5    1562
 공범 EP6    1274
 공범 EP7     555
 공범 EP8     266
Name: count, dtype: int64

In [12]:
df_video.sort_values(['videoname','ct']).drop_duplicates('videoname', keep='last')[['viewcnt','videoname','ct']].reset_index(drop=True)

   viewcnt videoname                  ct
0  3180532    공범 EP1 2021-11-01 15:30:03
1  2199328    공범 EP2 2021-11-01 15:30:03
2  1671294    공범 EP3 2021-11-01 15:30:03
3  1818493    공범 EP4 2021-11-01 15:30:03
4  1503435    공범 EP5 2021-11-01 15:30:04
5  1750222    공범 EP6 2021-11-01 15:30:04
6  1630200    공범 EP7 2021-11-01 15:30:05
7  1289088    공범 EP8 2021-11-01 15:30:05

In [19]:
df[df['ct'] >='2021-10-03'].sort_values(['ct','channelname']).drop_duplicates('channelname')[['channelname','ct']].reset_index()

    index      channelname                  ct
0     393           논리왕 전기 2021-10-03 03:01:02
1     139            야전삽짱재 2021-10-03 03:01:02
2     266       츄정ChuJeong 2021-10-03 03:01:02
3     901       김농밀의 농밀한 삶 2021-10-03 03:01:03
4    1028      릴펄 Lilpearl 2021-10-03 03:01:03
5     520  와글와글 WagleWagle 2021-10-03 03:01:03
6     647              조나단 2021-10-03 03:01:03
7     774          형사!탐정되다 2021-10-03 03:01:03
8    1276    Balming Tiger 2021-10-03 03:01:04
9    1155    곽토리 kwak tori 2021-10-03 03:01:04
10     12              꽈뚜룹 2021-10-03 03:01:04

In [21]:
### 14