데이터 설명 : 비행탑승 경험 만족도 (satisfaction 컬럼 : ‘neutral or dissatisfied’ or satisfied ) (83123, 24) shape

In [1]:
import pandas as pd
x_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/x_train.csv")
y_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/y_train.csv")
x_test= pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/x_test.csv")

In [2]:
display(x_train.head())
display(y_train.head())

print(x_train.info())
print(x_test.info())

,ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,id
0,0,Female,Loyal Customer,54,Personal Travel,Eco,1068,3,4,3,...,5,5,3,5,3,5,3,47,22.0,NaN
1,2,Male,Loyal Customer,20,Personal Travel,Eco,1546,4,4,4,...,4,3,3,4,4,4,4,5,2.0,NaN
2,3,Male,Loyal Customer,59,Business travel,Business,2962,0,4,0,...,1,1,1,1,5,1,4,54,46.0,NaN
3,4,Male,Loyal Customer,35,Business travel,Eco Plus,106,5,4,4,...,5,2,1,5,4,4,5,130,121.0,NaN
4,5,Female,Loyal Customer,9,Business travel,Business,2917,3,3,3,...,4,4,4,5,4,3,4,0,0.0,NaN

   ID             satisfaction
0   0  neutral or dissatisfied
1   2  neutral or dissatisfied
2   3                satisfied
3   4                satisfied
4   5                satisfied

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83123 entries, 0 to 83122
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ID                                 83123 non-null  int64
 1   Gender                             83123 non-null  object
 2   Customer Type                      83123 non-null  object
 3   Age                                83123 non-null  int64
 4   Type of Travel                     83123 non-null  object
 5   Class                              83123 non-null  object
 6   Flight Distance                    83123 non-null  int64
 7   Inflight wifi service              83123 non-null  int64
 8   Departure/Arrival time convenient  83123 non-null  int64
 9   Ease of Online booking             83123 non-null  int64
 10  Gate location                      83123 non-null  int64
 11  Food and drink                     83123 non-null  int64
 12  Online boarding                    83123 non-null  int64
 13  Seat comfort                       83123 non-null  int64
 14  Inflight entertainment             83123 non-null  int64
 15  On-board service                   83123 non-null  int64
 16  Leg room service                   83123 non-null  int64
 17  Baggage handling                   83123 non-null  int64
 18  Checkin service                    83123 non-null  int64
 19  Inflight service                   83123 non-null  int64
 20  Cleanliness                        83123 non-null  int64
 21  Departure Delay in Minutes         83123 non-null  int64
 22  Arrival Delay in Minutes           82867 non-null  float64
 23  id                                 0 non-null      float64
dtypes: float64(2), int64(18), object(4)
memory usage: 15.2+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20781 entries, 0 to 20780
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ID                                 20781 non-null  int64
 1   Gender                             20781 non-null  object
 2   Customer Type                      20781 non-null  object
 3   Age                                20781 non-null  int64
 4   Type of Travel                     20781 non-null  object
 5   Class                              20781 non-null  object
 6   Flight Distance                    20781 non-null  int64
 7   Inflight wifi service              20781 non-null  int64
 8   Departure/Arrival time convenient  20781 non-null  int64
 9   Ease of Online booking             20781 non-null  int64
 10  Gate location                      20781 non-null  int64
 11  Food and drink                     20781 non-null  int64
 12  Online boarding                    20781 non-null  int64
 13  Seat comfort                       20781 non-null  int64
 14  Inflight entertainment             20781 non-null  int64
 15  On-board service                   20781 non-null  int64
 16  Leg room service                   20781 non-null  int64
 17  Baggage handling                   20781 non-null  int64
 18  Checkin service                    20781 non-null  int64
 19  Inflight service                   20781 non-null  int64
 20  Cleanliness                        20781 non-null  int64
 21  Departure Delay in Minutes         20781 non-null  int64
 22  Arrival Delay in Minutes           20709 non-null  float64
 23  id                                 20781 non-null  float64
dtypes: float64(2), int64(18), object(4)
memory usage: 3.8+ MB
None

In [3]:
print(x_train.isna().sum())
print(x_test.isna().sum())

ID                                       0
Gender                                   0
Customer Type                            0
Age                                      0
Type of Travel                           0
Class                                    0
Flight Distance                          0
Inflight wifi service                    0
Departure/Arrival time convenient        0
Ease of Online booking                   0
Gate location                            0
Food and drink                           0
Online boarding                          0
Seat comfort                             0
Inflight entertainment                   0
On-board service                         0
Leg room service                         0
Baggage handling                         0
Checkin service                          0
Inflight service                         0
Cleanliness                              0
Departure Delay in Minutes               0
Arrival Delay in Minutes               256
id                                   83123
dtype: int64
ID                                    0
Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Ease of Online booking                0
Gate location                         0
Food and drink                        0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
On-board service                      0
Leg room service                      0
Baggage handling                      0
Checkin service                       0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
Arrival Delay in Minutes             72
id                                    0
dtype: int64

In [4]:
x_train['Arrival Delay in Minutes'] = x_train['Arrival Delay in Minutes'].fillna(x_train['Arrival Delay in Minutes'].mean())
x_test['Arrival Delay in Minutes'] = x_test['Arrival Delay in Minutes'].fillna(x_test['Arrival Delay in Minutes'].mean())

In [5]:
print(x_train.isna().sum())
print(x_test.isna().sum())

ID                                       0
Gender                                   0
Customer Type                            0
Age                                      0
Type of Travel                           0
Class                                    0
Flight Distance                          0
Inflight wifi service                    0
Departure/Arrival time convenient        0
Ease of Online booking                   0
Gate location                            0
Food and drink                           0
Online boarding                          0
Seat comfort                             0
Inflight entertainment                   0
On-board service                         0
Leg room service                         0
Baggage handling                         0
Checkin service                          0
Inflight service                         0
Cleanliness                              0
Departure Delay in Minutes               0
Arrival Delay in Minutes                 0
id                                   83123
dtype: int64
ID                                   0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
id                                   0
dtype: int64

In [6]:
x_train_drop = x_train.drop(columns = ['ID', 'id'])
x_test_drop = x_test.drop(columns = ['ID', 'id'])

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

x_train_dum = pd.get_dummies(x_train_drop)
x_test_dum = pd.get_dummies(x_test_drop)
x_test_dum = x_test_dum[x_train_dum.columns]

y = y_train['satisfaction']

In [8]:
x_train, x_val, y_train, y_val = train_test_split(x_train_dum, y, test_size=0.3, random_state=23)
rf = RandomForestClassifier(random_state=23)
rf.fit(x_train,y_train)

RandomForestClassifier(random_state=23)

In [9]:
from sklearn.metrics import accuracy_score, f1_score, recall_score, roc_auc_score, precision_score

predict_train = rf.predict(x_train)
predict_train_proba = rf.predict_proba(x_train)[:,0]

predict_val = rf.predict(x_val)
predict_val_proba = rf.predict_proba(x_val)[:,0]

In [10]:

print('--accuracy_score--')
print(accuracy_score(y_train, predict_train))
print(accuracy_score(y_val, predict_val))
print()
print('--f1_score--')
print(f1_score(y_train, predict_train, pos_label = 'neutral or dissatisfied'))
print(f1_score(y_val, predict_val, pos_label = 'neutral or dissatisfied'))
print()
print('--recall_score--')
print(recall_score(y_train, predict_train, pos_label = 'neutral or dissatisfied'))
print(recall_score(y_val, predict_val, pos_label = 'neutral or dissatisfied'))
print()
print('--roc_auc_score--')
print(roc_auc_score(y_train, predict_train_proba))
print(roc_auc_score(y_val, predict_val_proba))
print()
print('--precision_score--')
print(precision_score(y_train, predict_train, pos_label = 'neutral or dissatisfied'))
print(precision_score(y_val, predict_val, pos_label = 'neutral or dissatisfied'))

# pos_label -> 라벨이 문자로 표현된 경우 or 관심 클래스를 지정해야 하는 경우

--accuracy_score--
1.0
0.9608212695993905

--f1_score--
1.0
0.965847519837802

--recall_score--
1.0
0.9788153606348307

--roc_auc_score--
0.0
0.0060321203338488776

--precision_score--
1.0
0.9532187952804803

In [11]:
# 클래스 확인
# sklearn은 기본적으로 많은 값을 0번 클래스에 배치
print(y_train.value_counts())

satisfaction
neutral or dissatisfied    32989
satisfied                  25197
Name: count, dtype: int64

In [12]:
predict_test = rf.predict(x_test_dum)
predict_test_proba = rf.predict_proba(x_test_dum)[:,0]

pd.DataFrame({'ID': x_test.ID, 'satisfaction': predict_test}).to_csv('result.csv', index=False)